### ISSUE TITLE
About 8 frames FVD

### ISSUE THREAD

**Issue by fradino** [JunyaoHu/common_metrics_on_video_quality#3]
Hello, how can I calculate the FVD of 8 frames short video? Thank you!

**Comment by JunyaoHu** [comment]
Hello, thanks for your issue. I have to say, I have this problem with this code. Since the i3d model downsamples the video in the temporal dimension, videos have a lower bound on duration, which I think is an open problem. If the FVD does not meet your needs, you can try other assessment methods. 

For example, in our task, video prediction, we will calculate FVD when the video length > 8. In BAIR dataset, researchers usually use 2 conditional frames to prediction 5 (or other numers) frames once a time, but they do not calculate FVD of 7=2+5 frames. They will predict more time to extent the future frames to 14/28, then calculate FVD of 16=2+14 /30=2+28 frames. 

Another relative issue: https://github.com/google-deepmind/kinetics-i3d/issues/80: discussed how to process long and short videos, but it is not useful for our torchscript model.

Sorry I can't provide a good solution, but I hope the above information can help you.
