### ISSUE TITLE
difference between i3d_pretrained_400.pt and i3d_torchscript.pt

### ISSUE THREAD

**Issue by pixeli99** [JunyaoHu/common_metrics_on_video_quality#4]
What's the difference between i3d_pretrained_400.pt and i3d_torchscript.pt? I don't know much about this.

How do I use it when I test fvd?

**Comment by JunyaoHu** [comment]
@pixeli99  Hello, I am so sorry for my late response... First of all, let me correct you. It's not a stupid question.... It puzzled me for a long time, but I didn't want to know how and why. Now it seems that I have figured out, so let me answer your question about the 2 pretrained i3d models.

## TLDR

They almost do not have any difference, and you can randomly choose a model to calculate FVD. Their results are almost identical. And I have updated the repo, which has supported two FVD calculation methods (videogpt and styleganv). Welcome to use! 

![image](https://github.com/JunyaoHu/common_metrics_on_video_quality/assets/67564714/cc890415-2a1b-4e02-bd20-a5e425a99ffa)


![image](https://github.com/JunyaoHu/common_metrics_on_video_quality/assets/67564714/3a212c04-f56a-42a1-a936-eb9d6695bf4f)


## about 2 FVD models

### i3d_torchscript.pt

I use this model first, because I run based on [MCVD project](https://github.com/voletiv/mcvd-pytorch). From the code [comment](https://github.com/voletiv/mcvd-pytorch/blob/451da2eb635bad50da6a7c03b443a34c6eb08b3a/models/fvd/fvd.py#L29-L38), I know this fvd calculation method comes from repo fvd-comparison [here](https://github.com/universome/fvd-comparison), and fvd-comparison is the calculation method of [StyleGAN-V](https://github.com/universome/stylegan-v).

i3d_torchscript.pt is a precise implementation of the official one.  It is a torchscript model, and you don't need a model python file to create a i3d model first. 

![image](https://github.com/JunyaoHu/common_metrics_on_video_quality/assets/67564714/243c95b3-fddb-4a77-a89e-b3e5ed0a9269)

Download link: https://www.dropbox.com/s/ge9e5ujwgetktms/i3d_torchscript.pt

### i3d_pretrained_400.pt

The model is from [videogpt](https://github.com/wilson1yan/VideoGPT), and they say the model is the torch-version of [google's  origin fvd model](https://github.com/google-research/google-research/tree/master/frechet_video_distance). The use [a convertion python file](https://github.com/wilson1yan/VideoGPT/blob/master/videogpt/fvd/convert_tf_pretrained.py) to convert the origin tensorflow fvd model into pytorch. 

![image](https://github.com/JunyaoHu/common_metrics_on_video_quality/assets/67564714/8aca3071-7a61-4871-8eda-4861daed1ed7)

Download link: https://onedrive.live.com/download?cid=78EEF3EB6AE7DBCB&resid=78EEF3EB6AE7DBCB%21199&authkey=AApKdFHPXzWLNyI

## usage

When you calculate FVD, now you can choose any method / pretrained model.

```
    NUMBER_OF_VIDEOS = 8
    VIDEO_LENGTH = 50
    CHANNEL = 3
    SIZE = 64
    videos1 = torch.zeros(NUMBER_OF_VIDEOS, VIDEO_LENGTH, CHANNEL, SIZE, SIZE, requires_grad=False)
    videos2 = torch.ones(NUMBER_OF_VIDEOS, VIDEO_LENGTH, CHANNEL, SIZE, SIZE, requires_grad=False)
    device = torch.device("cuda")
    # device = torch.device("cpu")

    import json
    result = calculate_fvd(videos1, videos2, device, method='videogpt')
    print(json.dumps(result, indent=4))

    result = calculate_fvd(videos1, videos2, device, method='stylegan')
    print(json.dumps(result, indent=4))
```

---

Hope I can help you...

**Comment by pixeli99** [comment]
Thank you very much! It's very helpful to me.
